var assets_record = [
  {
    "id": 26,
    "operation": "BUY",
    "ticker": "BMGB4",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "CAPS",
    "exchange": "INTER",
    "amount": 40,
    "entry_price": "6.01",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 43,
    "operation": "BUY",
    "ticker": "CTNM4",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "CAPS",
    "exchange": "INTER",
    "amount": 67,
    "entry_price": "5.9",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 44,
    "operation": "BUY",
    "ticker": "TRIS3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "CAPS",
    "exchange": "INTER",
    "amount": 35,
    "entry_price": "11.5",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 4,
    "operation": "BUY",
    "ticker": "BBDC4",
    "ticker_type": "stock",
    "house": "personal",
    "strategy": "DIV",
    "exchange": "MODAL",
    "amount": 50,
    "entry_price": "30.4",
    "entry_date": "2020-02-27",
    "currency": "BRL"
  },
  {
    "id": 5,
    "operation": "BUY",
    "ticker": "BBDC4",
    "ticker_type": "stock",
    "house": "personal",
    "strategy": "DIV",
    "exchange": "CLEAR",
    "amount": 14,
    "entry_price": "28.42",
    "entry_date": "2020-03-02",
    "currency": "BRL"
  },
  {
    "id": 7,
    "operation": "BUY",
    "ticker": "ITSA4",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 16,
    "entry_price": "9.25",
    "entry_date": "2020-04-09",
    "currency": "BRL"
  },
  {
    "id": 11,
    "operation": "BUY",
    "ticker": "BBAS3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "38.87",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 13,
    "operation": "BUY",
    "ticker": "ENAT3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 30,
    "entry_price": "11.84",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 15,
    "operation": "BUY",
    "ticker": "ENBR3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "19.76",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 17,
    "operation": "BUY",
    "ticker": "CSMG3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 20,
    "entry_price": "16.24",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 22,
    "operation": "BUY",
    "ticker": "BRSR6",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "14.66",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 25,
    "operation": "BUY",
    "ticker": "BBDC3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "24.44",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 29,
    "operation": "BUY",
    "ticker": "ENAT3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 66,
    "entry_price": "12.16",
    "entry_date": "2021-01-07",
    "currency": "BRL"
  },
  {
    "id": 30,
    "operation": "BUY",
    "ticker": "CSMG3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 50,
    "entry_price": "16.08",
    "entry_date": "2021-01-07",
    "currency": "BRL"
  },
  {
    "id": 31,
    "operation": "BUY",
    "ticker": "BRSR6",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 55,
    "entry_price": "14.56",
    "entry_date": "2021-01-07",
    "currency": "BRL"
  },
  {
    "id": 32,
    "operation": "BUY",
    "ticker": "BBDC3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 34,
    "entry_price": "24.25",
    "entry_date": "2021-01-07",
    "currency": "BRL"
  },
  {
    "id": 37,
    "operation": "BUY",
    "ticker": "ENAT3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 30,
    "entry_price": "12.4",
    "entry_date": "2021-01-15",
    "currency": "BRL"
  },
  {
    "id": 38,
    "operation": "BUY",
    "ticker": "SAPR11",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "23.46",
    "entry_date": "2021-01-15",
    "currency": "BRL"
  },
  {
    "id": 48,
    "operation": "BUY",
    "ticker": "BRSR6",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 20,
    "entry_price": "13.69",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 49,
    "operation": "BUY",
    "ticker": "BBAS3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "34.39",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 50,
    "operation": "BUY",
    "ticker": "BBDC3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 9,
    "entry_price": "22.77",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 51,
    "operation": "BUY",
    "ticker": "ENAT3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 20,
    "entry_price": "12.18",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 52,
    "operation": "BUY",
    "ticker": "CSMG3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 17,
    "entry_price": "15.84",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 54,
    "operation": "BUY",
    "ticker": "BBAS3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 3,
    "entry_price": "28.81",
    "entry_date": "2021-02-22",
    "currency": "BRL"
  },
  {
    "id": 68,
    "operation": "BUY",
    "ticker": "EGIE3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 18,
    "entry_price": "41.07",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 69,
    "operation": "BUY",
    "ticker": "BRSR6",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 61,
    "entry_price": "12.19",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 70,
    "operation": "BUY",
    "ticker": "BBAS3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 25,
    "entry_price": "29.65",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 71,
    "operation": "BUY",
    "ticker": "MRVE3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "DIV",
    "exchange": "INTER",
    "amount": 43,
    "entry_price": "17.32",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 9,
    "operation": "BUY",
    "ticker": "western-asset-us-index-500-fi-multi",
    "ticker_type": "fund",
    "house": "personal",
    "strategy": "DOLAR",
    "exchange": "INTER",
    "amount": 283,
    "entry_price": "3.48",
    "entry_date": "2020-10-16",
    "currency": "BRL"
  },
  {
    "id": 72,
    "operation": "BUY",
    "ticker": "TESOURO DIRETO",
    "ticker_type": "fixa",
    "house": "personal",
    "strategy": "EMERGENCIA",
    "exchange": "INTER",
    "amount": 1,
    "entry_price": 1684,
    "entry_date": "2021-03-30",
    "currency": "BRL"
  },
  {
    "id": 74,
    "operation": "BUY",
    "ticker": "CDB MAIS LIMITE",
    "ticker_type": "fixa",
    "house": "personal",
    "strategy": "EMERGENCIA",
    "exchange": "INTER",
    "amount": 1,
    "entry_price": 2600,
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 1,
    "operation": "BUY",
    "ticker": "OIBR3",
    "ticker_type": "stock",
    "house": "personal",
    "strategy": "ESP",
    "exchange": "MODAL",
    "amount": 1,
    "entry_price": "1.07",
    "entry_date": "2019-07-16",
    "currency": "BRL"
  },
  {
    "id": 2,
    "operation": "BUY",
    "ticker": "OIBR3",
    "ticker_type": "stock",
    "house": "personal",
    "strategy": "ESP",
    "exchange": "CLEAR",
    "amount": 48,
    "entry_price": "0.94",
    "entry_date": "2019-12-03",
    "currency": "BRL"
  },
  {
    "id": 3,
    "operation": "BUY",
    "ticker": "CVCB3",
    "ticker_type": "stock",
    "house": "personal",
    "strategy": "ESP",
    "exchange": "MODAL",
    "amount": 12,
    "entry_price": "38.66",
    "entry_date": "2019-12-06",
    "currency": "BRL"
  },
  {
    "id": 6,
    "operation": "BUY",
    "ticker": "CVCB3",
    "ticker_type": "stock",
    "house": "personal",
    "strategy": "ESP",
    "exchange": "CLEAR",
    "amount": 32,
    "entry_price": "21.28",
    "entry_date": "2020-03-03",
    "currency": "BRL"
  },
  {
    "id": 18,
    "operation": "BUY",
    "ticker": "PRNR3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "ESP",
    "exchange": "INTER",
    "amount": 25,
    "entry_price": "8.77",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 33,
    "operation": "BUY",
    "ticker": "IRBR3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "ESP",
    "exchange": "INTER",
    "amount": 40,
    "entry_price": "7.72",
    "entry_date": "2021-01-08",
    "currency": "BRL"
  },
  {
    "id": 34,
    "operation": "BUY",
    "ticker": "TCSA3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "ESP",
    "exchange": "INTER",
    "amount": 30,
    "entry_price": "9.75",
    "entry_date": "2021-01-08",
    "currency": "BRL"
  },
  {
    "id": 35,
    "operation": "BUY",
    "ticker": "HBOR3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "ESP",
    "exchange": "INTER",
    "amount": 30,
    "entry_price": "11.05",
    "entry_date": "2021-01-08",
    "currency": "BRL"
  },
  {
    "id": 8,
    "operation": "BUY",
    "ticker": "HGRU11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 1,
    "entry_price": "114.11",
    "entry_date": "2020-06-15",
    "currency": "BRL"
  },
  {
    "id": 12,
    "operation": "BUY",
    "ticker": "HABT11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 5,
    "entry_price": "121.17",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 14,
    "operation": "BUY",
    "ticker": "RECT11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 5,
    "entry_price": "97.5",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 16,
    "operation": "BUY",
    "ticker": "VRTA11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 5,
    "entry_price": 118,
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 27,
    "operation": "BUY",
    "ticker": "HABT11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": 119,
    "entry_date": "2021-01-07",
    "currency": "BRL"
  },
  {
    "id": 28,
    "operation": "BUY",
    "ticker": "RECT11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 11,
    "entry_price": "97.55",
    "entry_date": "2021-01-07",
    "currency": "BRL"
  },
  {
    "id": 36,
    "operation": "BUY",
    "ticker": "HABT11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 4,
    "entry_price": "118.95",
    "entry_date": "2021-01-15",
    "currency": "BRL"
  },
  {
    "id": 39,
    "operation": "BUY",
    "ticker": "RECR11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 3,
    "entry_price": "111.9",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 40,
    "operation": "BUY",
    "ticker": "VRTA11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 3,
    "entry_price": "115.12",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 41,
    "operation": "BUY",
    "ticker": "RECT11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 4,
    "entry_price": 96,
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 42,
    "operation": "BUY",
    "ticker": "RBRR11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 4,
    "entry_price": "94.95",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 55,
    "operation": "BUY",
    "ticker": "VRTA11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 2,
    "entry_price": "114.86",
    "entry_date": "2021-03-17",
    "currency": "BRL"
  },
  {
    "id": 56,
    "operation": "BUY",
    "ticker": "RECR11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 2,
    "entry_price": "116.89",
    "entry_date": "2021-03-17",
    "currency": "BRL"
  },
  {
    "id": 57,
    "operation": "BUY",
    "ticker": "HABT11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 2,
    "entry_price": "119.23",
    "entry_date": "2021-03-17",
    "currency": "BRL"
  },
  {
    "id": 58,
    "operation": "BUY",
    "ticker": "RECT11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 2,
    "entry_price": "86.7",
    "entry_date": "2021-03-17",
    "currency": "BRL"
  },
  {
    "id": 59,
    "operation": "BUY",
    "ticker": "RBRP11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 8,
    "entry_price": "88.2375",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 60,
    "operation": "BUY",
    "ticker": "RECR11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 6,
    "entry_price": "107.92",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 61,
    "operation": "BUY",
    "ticker": "VRTA11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 6,
    "entry_price": "115.27",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 62,
    "operation": "BUY",
    "ticker": "RECT11",
    "ticker_type": "fii",
    "house": "VG",
    "strategy": "FII",
    "exchange": "INTER",
    "amount": 9,
    "entry_price": "81.39",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 73,
    "operation": "BUY",
    "ticker": "DEBENTURE ENGI49",
    "ticker_type": "fixa",
    "house": "personal",
    "strategy": "RESERVA",
    "exchange": "INTER",
    "amount": 1,
    "entry_price": "1337.32",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 10,
    "operation": "BUY",
    "ticker": "MDIA3",
    "ticker_type": "stock",
    "house": "personal",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 27,
    "entry_price": 37,
    "entry_date": "2020-10-21",
    "currency": "BRL"
  },
  {
    "id": 19,
    "operation": "BUY",
    "ticker": "ECOR3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "13.28",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 20,
    "operation": "BUY",
    "ticker": "BRML3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "9.98",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 21,
    "operation": "BUY",
    "ticker": "CCRO3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "13.48",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 23,
    "operation": "BUY",
    "ticker": "SBSP3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 7,
    "entry_price": "44.43",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 24,
    "operation": "BUY",
    "ticker": "BRPR3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 10,
    "entry_price": "9.89",
    "entry_date": "2020-12-30",
    "currency": "BRL"
  },
  {
    "id": 45,
    "operation": "BUY",
    "ticker": "BRPR3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 36,
    "entry_price": "9.29",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 46,
    "operation": "BUY",
    "ticker": "SBSP3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 8,
    "entry_price": "40.9",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 47,
    "operation": "BUY",
    "ticker": "COGN3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 73,
    "entry_price": "4.64",
    "entry_date": "2021-02-04",
    "currency": "BRL"
  },
  {
    "id": 63,
    "operation": "BUY",
    "ticker": "MDIA3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 27,
    "entry_price": "26.97",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 64,
    "operation": "BUY",
    "ticker": "VVAR3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 61,
    "entry_price": "11.98",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 65,
    "operation": "BUY",
    "ticker": "COGN3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 100,
    "entry_price": "3.88",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 66,
    "operation": "BUY",
    "ticker": "COGN3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 100,
    "entry_price": "3.88",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  },
  {
    "id": 67,
    "operation": "BUY",
    "ticker": "BRPR3",
    "ticker_type": "stock",
    "house": "VG",
    "strategy": "VALUE",
    "exchange": "INTER",
    "amount": 81,
    "entry_price": "9.17",
    "entry_date": "2021-04-30",
    "currency": "BRL"
  }
];
